一、环境：
  filebeat 版本： 6.4.2
二、配置

# 输入设置
filebeat.inputs:
- type: log
  # 开启收集（输入）
  enabled: true
  # 收集日志文件的路径，支持正则
  paths:
    - /var/log/*.log
  # 不以时间开头的行，合并到上面以时间开头的行的尾部
  multiline.pattern: ^[1-9]\d{3}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1]) (0[0-9]|1[0-9]|2[0-4]):([0-5][0-9]):([0-5][0-9])
  multiline.negate: false
  multiline.match: after

# 配置数据输出 至 logstash
output.logstash:
  hosts: ["localhost:5044"]




# logstash 配置和其他配置 请参数